version: "3.2"
services:
  gitexplorer:
    restart: always
    build:
      context: .
      cache_from:
        - node:14-alpine
    container_name: gitexplorer 
    hostname: gitexplorer 
    network_mode: bridge
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
    
